---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 30.09.2021 1:05
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), 0.1, false, function()
            if MAP == 1 then
                SetMainTheme()
            end
            DestroyTimer(GetExpiredTimer())
        end)
    end
end


function SetMainTheme()
    ClearMapMusicBJ()
    PlayMusicBJ("Sound\\Robots_a_Cometh")
    SetMusicVolumeBJ(100)
end