---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 20.08.2021 15:17
---
function CreateInterFaceMap2()
    CreateWayLost()
    CreateLiveSheep()
end

LivesSheep = 3
WayEnd = 28000
function CreateWayLost()
    local ico = "ReplaceableTextures\\CommandButtons\\BTNSpy"
    local Frame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(Frame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(Frame, ico, 0, true)
    BlzFrameSetSize(Frame, NextPoint / 2, NextPoint / 2)
    BlzFrameSetAbsPoint(Frame, FRAMEPOINT_CENTER, 0.85, 0.58 - (NextPoint / 2))
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", Frame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "")
    BlzFrameSetScale(text, 2)
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, Frame, FRAMEPOINT_LEFT, 0.015, 0.0)
    local total = math.abs(GetPlayerStartLocationX(Player(0))) + WayEnd
    --print(total,"total")
    TimerStart(CreateTimer(), 1, true, function()
        local dist = DistanceBetweenXY(WayEnd, 0, GetUnitXY(GCameraDummy))
        local percent = 100 - ((dist / total) * 100)
        maxSpeed = GetUnitMoveSpeed(GPlayer)/12
        minSpeed = GetUnitMoveSpeed(GPlayer)/70
        CompletedGame=R2I(percent)
        BlzFrameSetText(text, R2I(percent) .. "/" .. 100)
    end)
end

function CreateLiveSheep()
    local ico = "ReplaceableTextures\\CommandButtons\\BTNOrcDestroyer.blp"
    local Frame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(Frame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(Frame, ico, 0, true)
    BlzFrameSetSize(Frame, NextPoint / 2, NextPoint / 2)
    BlzFrameSetAbsPoint(Frame, FRAMEPOINT_CENTER, 0.85, 0.58 - 2 * (NextPoint / 2))
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", Frame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "")
    BlzFrameSetScale(text, 2)
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, Frame, FRAMEPOINT_LEFT, 0.015, 0.0)
    TimerStart(CreateTimer(), 1, true, function()
        BlzFrameSetText(text, LivesSheep)
    end)
end