---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.08.2021 19:34
---
function CreateAndMoveFrame(texture)
    local x,y=0.5,0.55
    local frame = CreateSimpleFrameGlue(x, y, texture, 1)

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        x=x-0.002
        BlzFrameSetAbsPoint(frame,FRAMEPOINT_CENTER,x,y)
        if x<=0.1 then
            DestroyTimer(GetExpiredTimer())
            BlzFrameSetVisible(frame,false)
        end
    end)
end

function StartCombiner()
    local textureTable = {
        "ReplaceableTextures\\CommandButtons\\BTNGolemStormBolt.blp",
        "ReplaceableTextures\\CommandButtons\\BTNParasite.blp",
        "ReplaceableTextures\\CommandButtons\\BTNCyclone.blp",
    }
    TimerStart(CreateTimer(), 1, true, function()
        local r=GetRandomInt(2,#textureTable)
        CreateAndMoveFrame(textureTable[r])
    end)
end