---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.08.2021 19:34
---

function CreateSimpleFrameGlueNew(posX, PosY, texture, flag)
    local NextPoint = 0.039
    if not texture then
        texture = "ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn"
    end
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
    BlzFrameSetSize(SelfFrame, NextPoint, NextPoint)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, posX, PosY)
    return SelfFrame
end

function CreateAndMoveFrame(texture)
    if not texture then
        return
    end
    local x, y = 0.5, 0.58 - 0.01
    local frame = CreateSimpleFrameGlueNew(x, y, texture, 1)
    local charge = 1
    if CompletedGame > 10 and CompletedGame < 20 then
        charge = 2
        MakeFrameCharged(frame, charge)
    elseif CompletedGame > 20 and CompletedGame < 30 then
        charge = 3
        MakeFrameCharged(frame, charge)
    elseif CompletedGame == 30 then
        BossFight = true
    else

    end

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        x = x - 0.002
        BlzFrameSetAbsPoint(frame, FRAMEPOINT_CENTER, x, y)
        if x <= 0.12 then
            DestroyTimer(GetExpiredTimer())
            BlzFrameSetVisible(frame, false)
            ActionPerDestroy(texture, charge)
        end
    end)
end

function StartCombiner()
    local textureTable = {
        "ReplaceableTextures\\CommandButtons\\BTNGolemStormBolt.blp",
        "ReplaceableTextures\\CommandButtons\\BTNParasite.blp",
        "ReplaceableTextures\\CommandButtons\\BTNCyclone.blp",
        "ReplaceableTextures\\CommandButtons\\BTNInnerFire.blp",
        "ReplaceableTextures\\CommandButtons\\BTNCryptFiendBurrow.blp",
        "ReplaceableTextures\\CommandButtons\\BTNTornado",
        "ReplaceableTextures\\CommandButtons\\BTNRepair",
        "ReplaceableTextures\\CommandButtons\\BTNDivineIntervention",
        "ReplaceableTextures\\CommandButtons\\BTNEvasion",
        "ReplaceableTextures\\CommandButtons\\BTNDemolish",
    }
    CreateCombinerUI()
    TimerStart(CreateTimer(), 1.5, true, function()
        local r = GetRandomInt(1, #textureTable)
        CreateAndMoveFrame(textureTable[r])
    end)

end

function CreateCombinerUI()
    local x, y = 0.318, 0.6
    local border = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(border, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(border, "CombainBorder", 0, true)
    BlzFrameSetSize(border, 0.4, 0.1)
    BlzFrameSetAbsPoint(border, FRAMEPOINT_TOP, x, y)

    for i = 1, 50 do
        -- print(i)
        CreateAndMoveChain(0.515 - i * (0.008) + 0.01, 0.58, nil, border)
    end

    TimerStart(CreateTimer(), 0.13, true, function()
        CreateAndMoveChain(0.515, 0.58, nil, border)
        --print(GetUnitMoveSpeed(GPlayer),"speed")
    end)
end

function CreateAndMoveChain(x, y, speed, border)
    local chain = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', border, '', 0)
    BlzFrameSetTexture(chain, "CombainChain", 0, true)
    BlzFrameSetSize(chain, 0.05, 0.05)
    BlzFrameSetAbsPoint(chain, FRAMEPOINT_TOP, x, y)

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        x = x - 0.002
        BlzFrameSetAbsPoint(chain, FRAMEPOINT_TOP, x, y)
        if x <= 0.12 then
            DestroyTimer(GetExpiredTimer())
            BlzFrameSetVisible(chain, false)
        end
    end)

end

function ActionPerDestroy(texture, charge)
    if not charge then
        charge = 1
    end
    if texture == "ReplaceableTextures\\CommandButtons\\BTNGolemStormBolt.blp" then
        --print("камень")
        for _ = 1, charge do
            CreateStone()
        end
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNParasite.blp" then
        --print("мурлок")
        for _ = 1, charge do
            CreateEnemy(FourCC("nmtw"))
        end
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNCyclone.blp" then
        --print("циклон")
        for _ = 1, charge do
            CreateTornado("ntor")
        end
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNInnerFire.blp" then
        local delay = 0.7
        --charge=3
        CreateEffectMarkDelay(delay, "EFFECT_Pack_1\\[Orbital Attack and laser's]\\Attack 3\\model (107).mdl", GetUnitX(GPlayer), GetUnitY(GPlayer))
        MarkPillar(GetUnitX(GPlayer), GetUnitY(GPlayer), Boss, delay)
        if charge > 1 then
            TimerStart(CreateTimer(), 0.5, true, function()
                CreateEffectMarkDelay(delay, "EFFECT_Pack_1\\[Orbital Attack and laser's]\\Attack 3\\model (107).mdl", GetUnitX(GPlayer), GetUnitY(GPlayer))
                MarkPillar(GetUnitX(GPlayer), GetUnitY(GPlayer), Boss, delay)
                charge = charge - 1
                if charge <= 0 then
                    DestroyTimer(GetExpiredTimer())
                end
            end)
        end
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNCryptFiendBurrow.blp" then

        local effmodel = "Doodads\\LordaeronSummer\\Terrain\\LoardaeronRockChunks\\LoardaeronRockChunks3"
        local effMark = CreateEffectMarkDelay(3, "EFFECT_Pack_1\\[Energy]\\Energy 3\\model (310).mdl", GetUnitX(GPlayer) + 200, GetUnitY(GPlayer))
        BlzSetSpecialEffectMatrixScale(effMark, 1, 1, 5)
        MarkAndFall(GetUnitX(GPlayer) + 200, GetUnitY(GPlayer), effmodel, Boss)
        if charge > 1 then
            TimerStart(CreateTimer(), 0.5, true, function()
                effMark = CreateEffectMarkDelay(3, "EFFECT_Pack_1\\[Energy]\\Energy 3\\model (310).mdl", GetUnitX(GPlayer) + 200, GetUnitY(GPlayer))
                BlzSetSpecialEffectMatrixScale(effMark, 1, 1, 5)
                MarkAndFall(GetUnitX(GPlayer) + 200, GetUnitY(GPlayer), effmodel, Boss)
                charge = charge - 1
                if charge <= 0 then
                    DestroyTimer(GetExpiredTimer())
                end
            end)
        end
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNTornado" then
        for _ = 1, charge do
            CreateTornado("n001")
        end
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNRepair" then
        CreateAmmo(texture)
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNDivineIntervention" then
        CreateAmmo(texture)
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNEvasion" then
        CreateAmmo(texture)
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNDemolish" then
        CreateAmmo(texture)
    else
        print('переданная текстура не найдена в базе', texture)
    end
end

function CreateStone()
    local xOffset = GetUnitX(GCameraDummy) + 1200
    local yOffset = GetUnitY(GCameraDummy) + GetRandomInt(-800, 200)
    CreateDestructableZ(FourCC("LTrc"), xOffset, yOffset, -50, 0, .95, GetRandomInt(1, 5))
end

function CreateEnemy(id)
    local xOffset = GetUnitX(GCameraDummy) + 1200
    local yOffset = GetUnitY(GCameraDummy) + GetRandomInt(-800, 200)
    local unit = CreateUnit(Player(5), id, xOffset, yOffset, 270)
    IssuePointOrder(unit, "attack", Gxs, Gys)
end

function CreateTornado(id)
    local xOffset = GetUnitX(GCameraDummy) + 1200
    local yOffset = GetUnitY(GCameraDummy) + GetRandomInt(-800, 200)
    local unit = CreateUnit(Player(5), FourCC(id), xOffset, yOffset, 270)
    UnitApplyTimedLife(unit, FourCC('BTLF'), 20)
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        SetUnitPositionSmooth(unit, GetUnitX(unit) - 3, GetUnitY(unit))
        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function CreateAmmo(texture)
    local xOffset = GetUnitX(GCameraDummy) + 1200
    local yOffset = GetUnitY(GCameraDummy) + GetRandomInt(-800, 200)
    local unit = CreateUnit(Player(PLAYER_NEUTRAL_PASSIVE), FourCC("n000"), xOffset, yOffset, 270)
    UnitAddAbility(unit, FourCC("Aloc"))
    local eff = AddSpecialEffect(GetEffectFromTexture(texture), xOffset - 20, yOffset)
    BlzSetSpecialEffectZ(eff, -10)
    local thisTrigger = CreateTrigger()
    TriggerRegisterUnitInRange(thisTrigger, unit, 100, nil)
    TriggerAddAction(thisTrigger, function()
        if GetUnitTypeId(GetTriggerUnit()) == FourCC("odes") then
            KillUnit(unit)
            ShowUnit(unit, false)
            DestroyEffect(eff)
            BlzSetSpecialEffectZ(eff, -300)
            DestroyTrigger(thisTrigger)
            ActionAmmo(GetTriggerUnit(), texture)
            local x, y = GetUnitXY(GetTriggerUnit())
            normal_sound("Abilities\\Spells\\Other\\LoadUnload\\Loading", x, y)
        end
    end)
end

function GetEffectFromTexture(texture)
    local s = string.gsub(texture, "ReplaceableTextures\\CommandButtons\\BTN", "Action")
    --print(s)
    return s
end

function ActionAmmo(unit, texture)
    if texture == "ReplaceableTextures\\CommandButtons\\BTNRepair" then
        HealUnit(unit, 50)
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNDivineIntervention" then
        --print("Неуязвимость")
        UnitAddAbility(unit, FourCC("AInv"))
        UnitAddItemById(unit, FourCC("I000"))
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNEvasion" then
        UnitAddBigAura(unit, 5)
    elseif texture == "ReplaceableTextures\\CommandButtons\\BTNDemolish" then
        UnitDestroyAura(unit, 5)
    end
end
