---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 20.08.2021 15:49
---
function InitDeathEvent()
    local this = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_UNIT_DEATH)
    TriggerAddAction(this, function()
        local u = GetTriggerUnit()
        local killer = GetKillingUnit()
        if GetUnitTypeId(u)==FourCC("odes") then
            LivesSheep=LivesSheep-1
            if LivesSheep<0 then
                LivesSheep=0
                CustomDefeatBJ(Player(0),"Больше нет запасных кораблей")
            else
                local x,y=GetUnitXY(GCameraDummy)
                --print("Воскрешаем")
                GPlayer=CreateUnit(Player(0),FourCC("odes"),x-2000,y-200,0)
                RebaseAbility(GPlayer)
                UnitDestroyAura(GPlayer,2)
                --GPlayer = River[1].GetSheep()
            end
        end
    end)
end