---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 20.08.2021 14:26
---
function CreateEffectMarkDelay(delay, effModel, x, y)
    local eff = AddSpecialEffect(effModel, x, y)
    TimerStart(CreateTimer(), delay, false, function()
        DestroyEffect(eff)
        BlzSetSpecialEffectPosition(eff, 5000, 5000, 00)
    end)
    return eff
end