---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.08.2021 19:59
---

function CreateAndMoveCamera(dummy, speed, xs, ys, flag)

    local X, Y = xs, ys
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        local unitPos = { GetUnitX(dummy), GetUnitY(dummy) }
        local endX, endY = table.unpack(vectorCut(unitPos, { X, Y }, -speed / vectorLen(unitPos, { X, Y })))
        SetUnitPositionSmooth(dummy, endX, endY)
        --print(endX)
        if flag then
            SetCameraTargetControllerNoZForPlayer(GetOwningPlayer(dummy), dummy, 10, 10, true)
        end
    end)
end

function Move2Mouse(hero)
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        local X, Y = MouseX, MouseY
        local unitPos = { GetUnitX(hero), GetUnitY(hero) }
        local speed0 = math.min(vectorLen(unitPos, { X, Y }) / 75, 30)
        if speed0<=5 then
            speed0=5
        end
        local speed = speed0 / vectorLen(unitPos, { X, Y })
        --print(speed0)
        local endX, endY = table.unpack(vectorCut(unitPos, { X, Y }, speed))
        local angle = -180 + AngleBetweenXY(X, Y, GetUnitX(hero), GetUnitY(hero)) / bj_DEGTORAD
        --(Y > endY) and look(unitPos, { 0, 0 }, unitPos, { X, Y }) or 360 - look(unitPos, { 0, 0 }, unitPos, { X, Y })
        --print(X)
        if X~=0 then
            SetUnitFacing(hero, angle)
            SetUnitPositionSmooth(hero, endX, endY)

        end
    end)
end