---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 09.08.2021 23:31
---

function vectorCut(a, b, delta)
    local x = (a[1] + delta * b[1]) / (1 + delta)
    local y = (a[2] + delta * b[2]) / (1 + delta)
    return { x, y }
end
function vectorLen(a, b)
    return math.sqrt((a[1] - b[1]) ^ 2 + (a[2] - b[2]) ^ 2)
end
function look(a1, a2, b1, b2)
    local AB = { a1[1] - a2[1], a1[2] - a2[2] }
    local AC = { b1[1] - b2[1], b1[2] - b2[2] }
    local scalar = AB[1] * AC[1] + AB[2] * AC[2]
    local len1 = math.sqrt(AB[1] ^ 2 + AB[2] ^ 2)
    local len2 = math.sqrt(AC[1] ^ 2 + AC[2] ^ 2)
    local acos = math.acos(scalar / (len1 * len2))
    local deg = math.deg(acos)
    return deg
end


function Init2Map() --вызывается из гуи
    local xs, ys = GetPlayerStartLocationX(Player(0)), GetPlayerStartLocationY(Player(0))
    Gxs, Gys = xs, ys
    MaxX=Gxs
    --print(xs)
    StartCombiner()
    local dummy = CreateUnit(Player(0), FourCC('owyv'), xs, ys, 0)
    GCameraDummy = dummy
    CreateAndMoveCamera(dummy, 1.8, xs, ys, true)

    local heroSheep = CreateUnit(Player(0), FourCC('odes'), xs, ys, 0)
    GPlayer=heroSheep
    CreateAndMoveCamera(heroSheep, 2.5, xs, ys)
    UnitAddAbility(heroSheep, FourCC('Apxf'))

    Move2Mouse(heroSheep)
    MouseX, MouseY = xs, ys

    local ThisTrigger = CreateTrigger()
    TriggerRegisterPlayerEvent(ThisTrigger, Player(0), EVENT_PLAYER_MOUSE_MOVE)
    TriggerAddAction(ThisTrigger, function()
        MouseX, MouseY = BlzGetTriggerPlayerMouseX(), BlzGetTriggerPlayerMouseY()
    end)
end