---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.08.2021 10:06
---
function UnitAddBigAura(unit)
    local prevX = GetUnitX(unit)
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        local x,y = GetUnitXY(unit)
        if x == prevX then
            --print("Стоит на месте")
        else
            --print("двигается")

            local e = nil
            local k = 0

            GroupEnumUnitsInRange(perebor, x,y,150, nil)
            while true do
                e = FirstOfGroup(perebor)

                if e == nil then
                    break
                end
                if UnitAlive(e) and e~=unit then
                    k = k + 1
                    local angle=AngleBetweenUnits(unit,e)
                    UnitAddForceSimple(e,angle,5,150)
                end
                GroupRemoveUnit(perebor, e)
            end
        end
        prevX = x
    end)
end