---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 31.07.2021 22:40
---
DummyID = FourCC("e000")
function EmpathPeons(unit)
    local x, y = GetUnitXY(unit)
    local dummy = CreateUnit(GetOwningPlayer(unit), DummyID, x, y, 0)
    UnitAddAbility(dummy, FourCC("A000"))
    UnitApplyTimedLife(dummy, FourCC('BTLF'), 2)
    if IssueTargetOrder(dummy, "spiritlink", unit) then
        --print(GetUnitName(unit))
    end
end
perebor = CreateGroup()
PreviousRandomPeon=1
function GetRandomPeon()
    local unit = nil
    local e = nil
    local k = 0
    --print("ищем")
    local rg = {}

    GroupEnumUnitsInRect(perebor, bj_mapInitialPlayableArea, nil)
    while true do
        e = FirstOfGroup(perebor)

        if e == nil then
            break
        end
        if UnitAlive(e) and GetUnitTypeId(e) == FourCC("opeo") then
            k = k + 1
            rg[k] = e
            unit = e
            if k==1 then

            end
        end
        GroupRemoveUnit(perebor, e)
    end
    local rp=GetRandomInt(1,#rg)
    if rp==PreviousRandomPeon then
        rp=PreviousRandomPeon+1
        if rp>=#rg then
            rp=1
        end
    end
    PreviousRandomPeon=rp
    return rg[rp],k,rg
end