---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.08.2021 11:10
---
function AddQuest(compas, hero, qx, qy, questendunit)
    local x, y = GetUnitX(hero), GetUnitY(hero)
    local model = "AneuCaster"
    local player = GetOwningPlayer(hero)
    local data = HERO[GetPlayerId(player)]

    if GetLocalPlayer() ~= player then
        model = ""
    else
        --print("звук созданного квеста")
        StartSound(bj_questSecretSound)
    end
    local QuestPointer = AddSpecialEffect(model, x, y)
    BlzSetSpecialEffectPitch(QuestPointer, math.rad(-90))--/bj_DEGTORAD

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        local z = GetUnitZ(hero)
        local xc, yc = GetUnitX(hero), GetUnitY(hero)
        local Angle = AngleBetweenXY(xc, yc, qx, qy)
        local nx,ny=MoveXY(xc,yc,130,Angle / bj_DEGTORAD)
        BlzSetSpecialEffectPosition(QuestPointer, nx,ny, z + 50)
        BlzSetSpecialEffectYaw(QuestPointer, Angle)

        if IsUnitInRangeXY(hero, qx, qy, 300) then
            DestroyTimer(GetExpiredTimer())
            DestroyEffect(QuestPointer)
            data.Compass = nil
        end
    end)

end

--AddQuest(true,GetTriggerUnit(),GetRectCenterX(gg_rct_OgreDefPlace),GetRectCenterY(gg_rct_OgreDefPlace))
