---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.08.2021 14:24
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), 1, false, function()
            ReplaceID2ArrowMark(FourCC("e001"))
            DestroyTimer(GetExpiredTimer())
        end)
    end
end
function ReplaceID2ArrowMark(id)
    local tmp, k, all = FindUnitOfType(id)
    --print("найденно "..k.." а в таблице "..#all)
    for i = 1, #all do
        SetUnitInvulnerable(all[i], true)
        UnitAddAbility(all[i], FourCC("Aloc"))
        local thisTrigger = CreateTrigger()
        TriggerRegisterUnitInRange(thisTrigger, all[i], 200, nil)
        TriggerAddAction(thisTrigger, function()
            KillUnit(all[i])
        end)
    end
end