---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 31.07.2021 16:20
---
function CreateSpeechEffect(unit,effModel,duration)
    if not unit then
        unit=GetRandomPeon()
    end
    if not effModel then
        effModel="smileys_empty"
    end
    if effModel=="random" then
        local r=GetRandomInt(1,2)
        if r==1 then
            effModel="smileys_warn"
        elseif r==2 then
            effModel="smileys_quest"
        end
    end

    if not duration then
        duration=5
    end
    local eff = AddSpecialEffectTarget(effModel, unit, "overhead")
    TimerStart(CreateTimer(), duration, false, function()
        DestroyEffect(eff)
    end)
end

