---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.08.2021 22:45
---

function MarkAndFall(x,y,effModel,hero)
	local mark=AddSpecialEffect("Alarm",x,y)
	BlzSetSpecialEffectScale(mark,1)
	TimerStart(CreateTimer(), 2, false, function()

		local FallenEff=AddSpecialEffect(effModel,x,y)
		BlzSetSpecialEffectZ(FallenEff,2000)
		BlzSetSpecialEffectYaw(FallenEff, math.rad(GetRandomReal(0,360)))
		TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
			local z=BlzGetLocalSpecialEffectZ(FallenEff)
			BlzSetSpecialEffectZ(FallenEff,z-50)
			if z<=GetTerrainZ(x,y) then
				DestroyEffect(mark)
				BlzSetSpecialEffectPosition(mark,5000,5000,0)
				DestroyTimer(GetExpiredTimer())
				DestroyEffect(FallenEff)
				local nd=CreateDestructable(FourCC('LTrc'), x, y, 0, GetRandomInt(1, 1), GetRandomInt(1, 5))
				SetDestructableInvulnerable(nd,true)
				DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic",x,y))
				local  _,damaged=UnitDamageArea(hero,100,x,y,150) --при падении камня
				if IsUnitInRangeXY(damaged,x,y,60) then
					RemoveUnit(damaged)
					print("придавлен камнем")
				end

				TimerStart(CreateTimer(), 5, false, function()
					KillDestructable(nd)
				end)
			end
		end)
	end)
end