---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.08.2021 23:22
---
function StartDemonessa(boss)
    TimerStart(CreateTimer(), 2, true, function()
        local rp=GetRandomPeon()
        local x,y=GetUnitXY(rp)
        local effmodel = "Doodads\\LordaeronSummer\\Terrain\\LoardaeronRockChunks\\LoardaeronRockChunks3"
        local angle=GetUnitFacing(rp)
        local dist=GetRandomInt(0,500)
        x,y=MoveXY(x,y,dist,angle)
        MarkAndFall(x,y,effmodel,boss)
    end)
end